[
 { label :"Abbottabad" },
 { label :"Adezai" },
 { label :"Ali Bandar"  },
 { label :"Amir Chah" },
 { label :"Attock" },
 { label :"Ayubia" },
 { label :"Bahawalpur"  },
 { label :"Baden"},
 { label :"Bagh" },
 { label :"Bahawalnagar" },
 { label :"Burewala"},
 { label :"Banda Daud Shah"},
 { label :"Bannu district|Bannu"},
 { label :"Batagram"},
 { label :"Bazdar" },
 { label :"Bela" },
 { label :"Bellpat"  },
 { label :"Bhag" },
 { label :"Bhakkar"  },
 { label :"Bhalwal"  },
 { label :"Bhimber"  },
 { label :"Birote" },
 { label :"Buner"},
 { label :"Burj" },
 { label :"Chiniot"  },
 { label :"Chachro"  },
 { label :"Chagai" },
 { label :"Chah Sandan"},
 { label :"Chailianwala" },
 { label :"Chakdara"},
 { label :"Chakku" },
 { label :"Chakwal"  },
 { label :"Chaman" },
 { label :"Charsadda" },
 { label :"Chhatr" },
 { label :"Chichawatni"},
 { label :"Chitral"  },
 { label :"Dadu" },
 { label :"Dera Ghazi Khan"},
 { label :"Dera Ismail Khan" },
  { label :"Dalbandin" },
 { label :"Dargai" },
 { label :"Darya Khan"  },
 { label :"Daska"},
 { label :"Dera Bugti"  },
 { label :"Dhana Sar" },
 { label :"Digri"},
 { label :"Dina City|Dina" },
 { label :"Dinga"},
 { label :"Diplo, Pakistan|Diplo"},
 { label :"Diwana" },
 { label :"Dokri"},
 { label :"Drosh"},
 { label :"Duki" },
 { label :"Dushi"},
 { label :"Duzab"},
 { label :"Faisalabad"  },
 { label :"Fateh Jang"  },
 { label :"Ghotki" },
 { label :"Gwadar" },
 { label :"Gujranwala"  },
 { label :"Gujrat" },
 { label :"Gadra"},
 { label :"Gajar"},
 { label :"Gandava"  },
 { label :"Garhi Khairo" },
 { label :"Garruck"  },
 { label :"Ghakhar Mandi"  },
 { label :"Ghanian"  },
 { label :"Ghauspur"},
 { label :"Ghazluna"},
 { label :"Girdan" },
 { label :"Gulistan"},
 { label :"Gwash"},
 { label :"Hyderabad" },
 { label :"Hala" },
 { label :"Haripur"  },
 { label :"Hab Chauki"  },
 { label :"Hafizabad" },
 { label :"Hameedabad"  },
 { label :"Hangu"},
 { label :"Harnai" },
 { label :"Hasilpur"},
 { label :"Haveli Lakha" },
 { label :"Hinglaj"  },
 { label :"Hoshab" },
 { label :"Islamabad" },
 { label :"Islamkot"},
 { label :"Ispikan"  },
 { label :"Jacobabad" },
 { label :"Jamshoro"},
 { label :"Jhang"},
 { label :"Jhelum" },
 { label :"Jamesabad" },
 { label :"Jampur" },
 { label :"Janghar"  },
 { label :"Jati, Jati(Mughalbhin)" },
 { label :"Jauharabad"  },
 { label :"Jhal" },
 { label :"Jhal Jhao" },
 { label :"Jhatpat"  },
 { label :"Jhudo"},
 { label :"Jiwani" },
 { label :"Jungshahi" },
 { label :"Karachi"  },
 { label :"Kotri"},
 { label :"Kalam"},
 { label :"Kalandi"  },
 { label :"Kalat"},
 { label :"Kamalia"  },
 { label :"Kamararod" },
 { label :"Kamber" },
 { label :"Kamokey"  },
 { label :"Kanak"},
 { label :"Kandi"},
 { label :"Kandiaro"},
 { label :"Kanpur" },
 { label :"Kapip"},
 { label :"Kappar" },
 { label :"Karak City"  },
 { label :"Karodi" },
 { label :"Kashmor"  },
 { label :"Kasur"},
 { label :"Katuri" },
 { label :"Keti Bandar"},
 { label :"Khairpur"},
 { label :"Khanaspur" },
 { label :"Khanewal"},
 { label :"Kharan" },
 { label :"kharian"  },
 { label :"Khokhropur"  },
 { label :"Khora"},
 { label :"Khushab"  },
 { label :"Khuzdar"  },
 { label :"Kikki"},
 { label :"Klupro" },
 { label :"Kohan"},
 { label :"Kohat"},
 { label :"Kohistan"},
 { label :"Kohlu"},
 { label :"Korak"},
 { label :"Korangi"  },
 { label :"Kot Sarae" },
 { label :"Kotli"},
 { label :"Lahore" },
 { label :"Larkana"  },
 { label :"Lahri"},
 { label :"Lakki Marwat" },
 { label :"Lasbela"  },
 { label :"Latamber"},
 { label :"Layyah" },
 { label :"Leiah"},
 { label :"Liari"},
 { label :"Lodhran"  },
 { label :"Loralai"  },
 { label :"Lower Dir" },
 { label :"Shadan Lund"},
 { label :"Multan" },
 { label :"Mandi Bahauddin"},
 { label :"Mansehra"},
 { label :"Mian Chanu"  },
 { label :"Mirpur" },
 { label :"Moro, Pakistan|Moro" },
 { label :"Mardan" },
 { label :"Mach" },
 { label :"Madyan" },
 { label :"Malakand"},
 { label :"Mand" },
 { label :"Manguchar" },
 { label :"Mashki Chah"},
 { label :"Maslti" },
 { label :"Mastuj" },
 { label :"Mastung"  },
 { label :"Mathi"},
 { label :"Matiari"  },
 { label :"Mehar"},
 { label :"Mekhtar"  },
 { label :"Merui"},
 { label :"Mianwali"},
 { label :"Mianez" },
 { label :"Mirpur Batoro"  },
 { label :"Mirpur Khas"},
 { label :"Mirpur Sakro" },
 { label :"Mithi"},
 { label :"Mongora"  },
 { label :"Murgha Kibzai"  },
 { label :"Muridke"  },
 { label :"Musa Khel Bazar"},
 { label :"Muzaffar Garh"  },
 { label :"Muzaffarabad" },
 { label :"Nawabshah" },
 { label :"Nazimabad" },
 { label :"Nowshera"},
 { label :"Nagar Parkar" },
 { label :"Nagha Kalat"},
 { label :"Nal"},
 { label :"Naokot" },
 { label :"Nasirabad" },
 { label :"Nauroz Kalat" },
 { label :"Naushara"},
 { label :"Nur Gamma" },
 { label :"Nushki" },
 { label :"Nuttal" },
 { label :"Okara"},
 { label :"Ormara" },
 { label :"Peshawar"},
 { label :"Panjgur"  },
 { label :"Pasni City"  },
 { label :"Paharpur"},
 { label :"Palantuk"},
 { label :"Pendoo" },
 { label :"Piharak"  },
 { label :"Pirmahal"},
 { label :"Pishin" },
 { label :"Plandri"  },
 { label :"Pokran" },
 { label :"Pounch" },
 { label :"Quetta" },
 { label :"Qambar" },
 { label :"Qamruddin Karez"},
 { label :"Qazi Ahmad"  },
 { label :"Qila Abdullah"  },
 { label :"Qila Ladgasht"  },
 { label :"Qila Safed"  },
 { label :"Qila Saifullah"},
 { label :"Rawalpindi"  },
 { label :"Rabwah" },
 { label :"Rahim Yar Khan"},
 { label :"Rajan Pur" },
 { label :"Rakhni" },
 { label :"Ranipur"  },
 { label :"Ratodero"},
 { label :"Rawalakot" },
 { label :"Renala Khurd" },
 { label :"Robat Thana"},
 { label :"Rodkhan"  },
 { label :"Rohri"},
 { label :"Sialkot"  },
 { label :"Sadiqabad" },
 { label :"Safdar Abad- (Dhaban Singh)"  },
 { label :"Sahiwal"  },
 { label :"Saidu Sharif" },
 { label :"Saindak"  },
 { label :"Sakrand"  },
 { label :"Sanjawi"  },
 { label :"Sargodha"},
 { label :"Saruna" },
 { label :"Shabaz Kalat" },
 { label :"Shadadkhot"  },
 { label :"Shahbandar"  },
 { label :"Shahpur"  },
 { label :"Shahpur Chakar"},
 { label :"Shakargarh"  },
 { label :"Shangla"  },
 { label :"Sharam Jogizai"},
 { label :"Sheikhupura"},
 { label :"Shikarpur" },
 { label :"Shingar"  },
 { label :"Shorap" },
 { label :"Sibi" },
 { label :"Sohawa" },
 { label :"Sonmiani"},
 { label :"Sooianwala"  },
 { label :"Spezand"  },
 { label :"Spintangi" },
 { label :"Sui"},
 { label :"Sujawal"  },
 { label :"Sukkur" },
 { label :"Suntsar"  },
 { label :"Surab"},
 { label :"Swabi"},
 { label :"Swat" },
 { label :"Tando Adam"  },
 { label :"Tando Bago"  },
 { label :"Tangi"},
 { label :"Tank City" },
 { label :"Tar Ahamd Rind"},
 { label :"Thalo"},
 { label :"Thatta" },
 { label :"Toba Tek Singh"},
 { label :"Tordher"  },
 { label :"Tujal"},
 { label :"Tump" },
 { label :"Turbat" },
 { label :"Umarao" },
 { label :"Umarkot"  },
 { label :"Upper Dir" },
 { label :"Uthal"},
 { label :"Vehari" },
 { label :"Veirwaro"},
 { label :"Vitakri"  },
 { label :"Wadh" },
 { label :"Wah Cantt" },
 { label :"Warah"},
 { label :"Washap" },
 { label :"Wasjuk" },
 { label :"Wazirabad" },
 { label :"Yakmach"  },
 { label :"Zhob" },
 { label :"Other"},
]